### PR TITLE
Added tests for new builtins

### PR DESCRIPTION
**Pull request by arduano**
Hey, this PR goes in tandem with https://github.com/urbas/nixjs-rt/pull/48. It has all the context.

### CODE REVIEW

**Comment by urbas** [comment]
Github actions didn't run. Looks like I'll have to revert 0537628a2b6916dc64e0135c3e6651b3cee70a36 to enable builds for PRs from other repos.

**Comment by arduano** [comment]
Should I push a new commit or something? to trigger actions

**Comment by urbas** [comment]
@arduano: Yes please, could you rebase on master. It should do the build after that.

Also, you will have to bump the flake inputs. Take a look at [these instructions](https://github.com/urbas/rix/blob/master/CONTRIBUTE.md#updating-dependencies) on how to do that.

**Comment by arduano** [comment]
I'm honestly confused what the workflow error is

**Comment by urbas** [comment]
The test failure is unrelated to your change and is likely related to the flake update. I'll take a look at it, but will likely take me until Monday. I hope that's okay.

**Comment by urbas** [comment]
Should be fixed in #106

**Pull request merged**
