### PR TITLE
Some fixes to the previous PR

### PR DESCRIPTION
**Pull request by arduano**
I think some things got missed in the previous PR when you merged, just another PR fixing them

### CODE REVIEW

**Review by urbas — APPROVED** [review]

**Comment by arduano** [comment]
@arduano I know I've been doing a lot of reactors on your code, but is there anything you'd prefer I don't touch because you wanna work on it yourself? Also any particular directions you'd prefer that I focus on?

If nothing else, I'll just start fixing up the tests, and then continue adding more builtins.

**Comment by arduano** [comment]
@urbas I know I've been doing a lot of reactors on your code, but is there anything you'd prefer I don't touch because you wanna work on it yourself? Also any particular directions you'd prefer that I focus on?

If nothing else, I'll just start fixing up the tests, and then continue adding more builtins.

**Comment by urbas** [comment]
> @urbas I know I've been doing a lot of refactors on your code, but is there anything you'd prefer I don't touch because you wanna work on it yourself? Also any particular directions you'd prefer that I focus on?

Oh, no worries, no code is out of limits.

I would like to start working on source-mapping and the ability to use v8 profilers, but if you want to work on that then by all means. I'll find something else to work on. Shouldn't be a problem.

Just for full disclosure, I might be a bit annoying at times because I like to apply constant pressure against code complexity. So I apologise for that in advance 🙈

> 
> If nothing else, I'll just start fixing up the tests, and then continue adding more builtins.

That sounds great!

Thank you very much for all the amazing work! Right now you're single-handedly driving the project and giving it life, but I'll definitely contribute now that I see this project has some value in other people's eyes too.

Many many thanks! 🙌🎉

**Comment by arduano** [comment]
> I would like to start working on source-mapping and the ability to use v8 profilers
Yeah that sounds nice, along with actually having stack traces in errors (I skipped doing that), etc

> I like to apply constant pressure against code complexity
lol fair, and I'll be the one applying pressure against best practices and development velocity (e.g. with me pushing for easier testing or splitting up the massive files to be more manageable haha)

**Pull request merged**
